version: "3.5"

services:

  sftp:
    ports:
      - '22:22'
    container_name: sftp
    build: ./sftp-storage
    volumes:
      - ./sftp-storage/contents:/home/demo/sftp/

  airflow:
    build: ./airflow
    restart: always
    container_name: airflow
    volumes:
      - ./airflow/config/airflow.cfg:/usr/local/airflow/airflow.cfg
      - ./airflow/config/dags:/usr/local/airflow/dags
      - ./srflp-solver:/usr/local/airflow/srflp-solver
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10

  mysql:
    build: ./mysql
    container_name: sftp_db